version: "3"
services:
  web:
    build: .
    image: registry.cn-hangzhou.aliyuncs.com/wjlin0/ctf:cve-cve-2024-23897
    platform: linux/amd64
    ports:
      - "9002:8080"
    environment:
      - FLAG=ctf{123456789}
