version: '3'
services:
  web:
    build: .
    image: registry.cn-hangzhou.aliyuncs.com/wjlin0/ctf:ssrf-php-004
    restart: always
    platform: linux/amd64
    ports:
      - "1404:80"
    environment:
      - FLAG=ctf{123456789}