version: '3'
services:
  web:
    build: .
    container_name: unserialize-php-005
    image: registry.cn-hangzhou.aliyuncs.com/wjlin0/ctf:unserialize-php-005
    restart: always
    platform: linux/amd64
    ports:
      - "1505:80"
    environment:
      - FLAG=ctf{123456789}