version: '3'
services:
  web:
    platform: linux/amd64
    build: .
    image: wjlin1/ctf:sql-postgresql-019
    restart: always
    ports:
      - "1319:80"
    environment:
      - FLAG=ctf{123456789}