version: '3'
services:
  web:
    build: .
    image: wjlin1/ctf:cve-cve-2024-25325
    restart: always
    platform: linux/amd64
    ports:
      - "9001:80"
    environment:
      - FLAG=ctf{123456789}