version: '3'
services:
  web:
    build: .
    image: registry.cn-hangzhou.aliyuncs.com/wjlin0/ctf:xxe-php-001
    restart: always
    platform: linux/amd64
    ports:
      - "1601:80"
    environment:
      - FLAG=ctf{123456789}